### ISSUE TITLE
Roll release compatible with Glide 2.0

### ISSUE THREAD

**Issue by bradjones1** [thephpleague/glide-symfony#12]
Support for Glide 2.0 was added in https://github.com/thephpleague/glide-symfony/commit/d727bbbfc77e0c0135b819c945aa67b9dfd48b4a - is it possible to roll a release for this?

**Comment by wimwinterberg** [comment]
Is there any work that can be done to roll out the release for support of glide 2.0 ?

**Comment by tgalopin** [comment]
Released: https://github.com/thephpleague/glide-symfony/releases/tag/1.1.0

**Comment by bradjones1** [comment]
Thank you.
